import React, { useEffect, useState, useCallback } from 'react'
import { payrollAPI } from '../api.js'

// Pick a pay period from a list generated by the facility's pay schedule —
// so a coordinator clicks "Jun 6 – Jun 20" instead of typing the span each
// run — with a Custom range fallback and a one-time schedule setup.
//
// Props: value = { start, end } (YYYY-MM-DD), onChange({ start, end }).

function fmtRange(start, end) {
  if (!start || !end) return ''
  const s = new Date(start + 'T00:00:00')
  const e = new Date(end + 'T00:00:00')
  const md = { month: 'short', day: 'numeric' }
  return `${s.toLocaleDateString('en-US', md)} – ${e.toLocaleDateString('en-US', md)}, ${e.getFullYear()}`
}

const inputStyle = { padding: '8px 10px', border: '1px solid #E2E8F0', borderRadius: 8, fontSize: 14, color: '#0F172A', outline: 'none' }

export default function PayrollPeriodPicker({ value, onChange }) {
  const [periods, setPeriods] = useState([])
  const [custom, setCustom] = useState(false)
  const [showSchedule, setShowSchedule] = useState(false)
  const [anchorDraft, setAnchorDraft] = useState('')
  const [freqDraft, setFreqDraft] = useState('BIWEEKLY')
  const [saving, setSaving] = useState(false)

  const load = useCallback(async () => {
    try {
      const res = await payrollAPI.getPayPeriods()
      setPeriods(res.periods || [])
      setAnchorDraft(res.anchorDate || '')
      setFreqDraft(res.frequency || 'BIWEEKLY')
      return res.periods || []
    } catch { return [] }
  }, [])

  // On mount: load periods, then snap to the most recent period that has
  // submitted hours (so you land on the payroll you're about to run) unless the
  // parent's value already matches a generated period.
  useEffect(() => {
    load().then((ps) => {
      const matches = ps.some((p) => p.start === value?.start && p.end === value?.end)
      if (!matches && ps.length) {
        const pick = ps.find((p) => p.submittedEntries > 0) || ps.find((p) => !p.hasRun) || ps[0]
        if (pick) onChange({ start: pick.start, end: pick.end })
      }
    })
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  const selectedKey = value ? `${value.start}|${value.end}` : ''
  const matchesPeriod = periods.some((p) => `${p.start}|${p.end}` === selectedKey)

  async function saveSchedule() {
    setSaving(true)
    try {
      await payrollAPI.setPaySchedule({ anchorDate: anchorDraft || null, frequency: freqDraft })
      const ps = await load()
      setShowSchedule(false)
      const pick = ps.find((p) => p.submittedEntries > 0) || ps[0]
      if (pick) onChange({ start: pick.start, end: pick.end })
    } finally { setSaving(false) }
  }

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 8, flexWrap: 'wrap' }}>
        <label style={{ fontSize: 12, fontWeight: 700, color: '#475569' }}>Pay period</label>
        {!custom ? (
          <select
            style={{ ...inputStyle, minWidth: 300 }}
            value={matchesPeriod ? selectedKey : ''}
            onChange={(e) => {
              if (e.target.value === '__custom__') { setCustom(true); return }
              const [start, end] = e.target.value.split('|')
              onChange({ start, end })
            }}
          >
            {!matchesPeriod && <option value="">Select a pay period…</option>}
            {periods.map((p) => {
              const status = p.hasRun
                ? ' · ✓ run'
                : p.submittedEntries > 0
                ? ` · ${p.providerCount} provider${p.providerCount === 1 ? '' : 's'} ready`
                : ' · no hours yet'
              return (
                <option key={`${p.start}|${p.end}`} value={`${p.start}|${p.end}`}>
                  {fmtRange(p.start, p.end)}{status}
                </option>
              )
            })}
            <option value="__custom__">Custom range…</option>
          </select>
        ) : (
          <>
            <input style={inputStyle} type="date" value={value?.start || ''} onChange={(e) => onChange({ start: e.target.value, end: value?.end || '' })} />
            <span style={{ color: '#94A3B8' }}>→</span>
            <input style={inputStyle} type="date" value={value?.end || ''} onChange={(e) => onChange({ start: value?.start || '', end: e.target.value })} />
            <button onClick={() => { setCustom(false); load() }} style={{ ...inputStyle, cursor: 'pointer', background: '#fff', color: '#2563EB', fontWeight: 600 }}>Use list</button>
          </>
        )}
        <button onClick={() => setShowSchedule((v) => !v)} style={{ background: 'none', border: 'none', color: '#64748B', fontSize: 13, cursor: 'pointer' }} title="Set your pay-period schedule once">⚙ Pay schedule</button>
      </div>

      {showSchedule && (
        <div style={{ display: 'flex', alignItems: 'center', gap: 10, flexWrap: 'wrap', padding: '10px 12px', background: '#F8FAFC', border: '1px solid #E2E8F0', borderRadius: 8 }}>
          <span style={{ fontSize: 12, color: '#64748B' }}>Set once — every pay period generates from it.</span>
          <label style={{ fontSize: 12, color: '#475569' }}>A pay period starts on</label>
          <input style={inputStyle} type="date" value={anchorDraft} onChange={(e) => setAnchorDraft(e.target.value)} />
          <select style={inputStyle} value={freqDraft} onChange={(e) => setFreqDraft(e.target.value)}>
            <option value="BIWEEKLY">Every 2 weeks</option>
            <option value="WEEKLY">Weekly</option>
          </select>
          <button onClick={saveSchedule} disabled={saving} style={{ ...inputStyle, cursor: saving ? 'default' : 'pointer', background: '#2563EB', color: '#fff', border: 'none', fontWeight: 700 }}>{saving ? 'Saving…' : 'Save schedule'}</button>
        </div>
      )}
    </div>
  )
}
